#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;
int main()
{
    int num, guess;
    srand(time(0));
    num = 1 + rand() % (100-1 +1);  
    
    cout<<"Welcome to the Guessing Game!";
    cout<<"The number is generated by the computer is:" << num << endl;

    cout << "Guess My Number Game\n\n";
    cout << "Enter a guess between 1 and 100 : ";
    cin >> guess;

    while(guess!=num)
    {
        if (guess > num)
        {
            cout << "Your Guess is Too high!\n\n";
        }
        else if (guess < num)
        {
            cout << "Your Guess is Too low!\n\n";
        }
        cin>>guess;
    }
    cout<<"Congratulation, You got it, My number Was :" << num << endl;
    system("pause");
    return 0;
}